[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["hhuuu"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "hhuuu"
  org = "manyworld"
  version = "1.0.1"

